feature: add client folder

diff --git a/.github/workflows/cron.yml b/.github/workflows/cron.yml
--- a/.github/workflows/cron.yml
+++ b/.github/workflows/cron.yml
@@ -16,7 +16,7 @@ env:
   DISCORD_TEAM_ID: ${{ secrets.DISCORD_FRONT_TEAM_ID }}
 
 jobs:
-  environment:
+  database:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -26,26 +26,8 @@ jobs:
           node-version: ${{ env.NODE_VERSION }}
 
       - name: Retrieve environment for database
-        run: echo "{{ env.ULTIMATE_ENV }}" > .env
+        run: echo "${{ env.ULTIMATE_ENV }}" > .env
         working-directory: ${{ env.DATABASE_DIRECTORY }}
-
-      - name: Retrieve environment for jobs
-        run: echo "{{ env.ULTIMATE_ENV }}" > .env
-        working-directory: ${{ env.JOBS_DIRECTORY }}
-
-      - name: Discord notification on failure
-        if: failure()
-        uses: ./.github/actions/discord/notification-on-failure
-
-  database:
-    runs-on: ubuntu-latest
-    needs: environment
-    steps:
-      - uses: actions/checkout@v3
-      - name: Use Node.js ${{ env.NODE_VERSION }}
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ env.NODE_VERSION }}
 
       - name: Install dependencies
         run: npm install
@@ -54,6 +36,14 @@ jobs:
       - name: Run script
         run: npm run generate
         working-directory: ${{ env.DATABASE_DIRECTORY }}
+
+      - name: Cache prisma client
+        uses: actions/cache@v3
+        with:
+          path: ${{ env.DATABASE_DIRECTORY }}/client/
+          key: dwaves-prisma-client-${{ github.run_id }}
+          restore-keys: |
+            dwaves-prisma-client-
 
       - name: Discord notification on failure
         if: failure()
@@ -68,6 +58,28 @@ jobs:
         with:
           node-version: ${{ env.NODE_VERSION }}
 
+      - name: Cache prisma client
+        id: prisma-client
+        uses: actions/cache@v3
+        with:
+          path: ${{ env.DATABASE_DIRECTORY }}/client/
+          key: dwaves-prisma-client-${{ github.run_id }}
+
+      - name: Cancel if prisma client is not cached
+        if: ${{ steps.prisma-client.outputs.cache-hit != 'true' }}
+        continue-on-error: false
+        run: echo "prisma client not found" && exit 1
+
+      - run: ls -al
+        working-directory: ${{ env.DATABASE_DIRECTORY }}
+
+      - name: Retrieve prisma client
+        run: mv ${{ env.DATABASE_DIRECTORY }}/client ${{ env.JOBS_DIRECTORY }}
+
+      - name: Retrieve environment for jobs
+        run: echo "${{ env.ULTIMATE_ENV }}" > .env
+        working-directory: ${{ env.JOBS_DIRECTORY }}
+
       - name: Install dependencies
         run: npm install
         working-directory: ${{ env.JOBS_DIRECTORY }}
@@ -76,8 +88,11 @@ jobs:
         run: npm run build
         working-directory: ${{ env.JOBS_DIRECTORY }}
 
+      - run: ls build/
+        working-directory: ${{ env.JOBS_DIRECTORY }}
+
       - name: Run script
-        run: npm start
+        run: node build/payArtists.js
         working-directory: ${{ env.JOBS_DIRECTORY }}
 
       - name: Discord notification on success
